# Generated by Django 5.1 on 2024-08-28 00:50

import autocare.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=10, verbose_name='Patente')),
                ('brand', models.CharField(choices=[('Honda', 'Honda'), ('Chevrolet', 'Chevrolet'), ('VW', 'VW'), ('Fiat', 'Fiat'), ('Jeep', 'Jeep'), ('Renault', 'Renault'), ('Citroen', 'Citroen'), ('Zuzuki', 'Zuzuki'), ('Nizzan', 'Nizzan'), ('Mercedes Benz', 'Mercedes Benz'), ('Subaru', 'Subaru'), ('Toyota', 'Toyota'), ('BYD', 'BYD'), ('Hyundai', 'Hyundai'), ('Peugeot', 'Peugeot'), ('Mazda', 'Mazda'), ('Chery', 'Chery'), ('Kia', 'Kia'), ('Ford', 'Ford'), ('Changan', 'Changan'), ('BMW', 'BMW'), ('Audi', 'Audi'), ('DFSK', 'DFSK'), ('Dodge', 'Dodge'), ('Faw', 'Faw'), ('Geely', 'Geely'), ('Haima', 'Haima'), ('Haval', 'Haval'), ('Jetour', 'Jetour'), ('JMC', 'JMC'), ('Land Rover', 'Land Rover'), ('Mitsubishi', 'Mitsubishi'), ('Seat', 'Seat'), ('Volvo', 'Volvo')], max_length=50, verbose_name='Marca')),
                ('moddel', models.CharField(max_length=50, verbose_name='Modelo')),
                ('year', models.IntegerField(default=autocare.models.Vehicle.current_year, verbose_name='Año de Fabricación')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('car_mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_mechanic', to=settings.AUTH_USER_MODEL, verbose_name='Mecánico Asignado')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_owner', to=settings.AUTH_USER_MODEL, verbose_name='Titular')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Servicio')),
                ('kilometers', models.IntegerField(default=0, verbose_name='Kilometraje')),
                ('service_type', models.CharField(choices=[('Filtro de aire', 'Filtro de aire'), ('Filtro de aceite', 'Filtro de aceite'), ('Cambio aceite', 'Cambio aceite'), ('Cambio pastillas de freno', 'Cambio pastillas de freno'), ('Filtro de combustible', 'Filtro de combustible'), ('Cambio de lubricación de transmisión', 'Cambio de lubricación de transmisión'), ('Cambio de amortiguadores', 'Cambio de amortiguadores'), ('Cambio de cubiertas', 'Cambio de cubiertas'), ('Cambio de batería', 'Cambio de batería'), ('Carga Combustible', 'Carga Combustible'), ('Chapista', 'Chapista'), ('Tren delantero', 'Tren delantero'), ('Electricidad', 'Electricidad'), ('Carga Nafta', 'Carga Nafta'), ('Pinchadura', 'Pinchadura'), ('Me hizo un ruido', 'Me hizo un ruido'), ('Cualquier otra cosa', 'Cualquier otra cosa')], max_length=500, verbose_name='Tipo de Servicio')),
                ('coments', models.TextField(blank=True, help_text='Indique cualquier cosa que desee comentar', verbose_name='Comentarios')),
                ('cost', models.IntegerField(verbose_name='Costo del Servicio')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha Servicio')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autocare.vehicle', verbose_name='Patente')),
            ],
        ),
    ]
