# Generated by Django 5.1 on 2024-10-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='mileage',
            field=models.CharField(default=1, max_length=50, verbose_name='Kilometraje'),
            preserve_default=False,
        ),
    ]
