# Generated by Django 5.1 on 2024-11-10 22:30

import autocare.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0002_vehicle_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(default=autocare.models.Vehicle.current_year, verbose_name='Año'),
        ),
    ]
