# Generated by Django 5.1 on 2024-12-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0003_alter_vehicle_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='mileage',
            field=models.IntegerField(verbose_name='Kilometraje'),
        ),
    ]
